---
secure:
  required_reviews: 1
  requires_mfa: true
build:
  engines:
    - ContainerTag:
        name: image
        path: ./Dockerfile
    - BaldurGem:
        name: gem
        path: ./Dockerfile-gem
