
version: 2
jobs:
  lint:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pkg-cache
      - run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/fc0a898a6ae297c0ef59e2f1d824713d6f1cd222/install.sh | sh -s -- -d -b $(go env GOPATH)/bin v1.27.0
      - run: golangci-lint --version
      - run: make lint
      - save_cache:
          key: v1-pkg-cache
          paths:
            - /go/pkg

  tests:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pkg-cache
      - run: make test
      - save_cache:
          key: v1-pkg-cache
          paths:
            - /go/pkg

  salus:
    machine: true
    steps:
      - checkout
      - run: docker run -t -v $(pwd):/home/repo coinbase/salus

workflows:
  version: 2
  build:
    jobs:
      - tests
      - lint
      - salus

