
version: 2
jobs:
  lint:
    docker:
      - image: cimg/go:1.16
    steps:
      - checkout
      - run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/fc0a898a6ae297c0ef59e2f1d824713d6f1cd222/install.sh | sh -s -- -d -b $(go env GOPATH)/bin v1.27.0
      - run: golangci-lint --version
      - run: make lint

  ruby-tests:
    docker:
      - image: cimg/ruby:2.7.1
      - image: grokzen/redis-cluster:6.0.9
        name: redis-cluster
        environment:
          SENTINEL: 'false'
          STANDALONE: '1'
    environment:
      GOLANG_DOWNLOAD_URL: https://golang.org/dl/go1.16.linux-amd64.tar.gz
      GOLANG_DOWNLOAD_SHA256: 013a489ebb3e24ef3d915abe5b94c3286c070dfe0818d5bca8108f1d6e8440d2
      GOPATH: /go
      REDIS_HOST: redis-cluster
    steps:
      - checkout
      - run:
          name: install go
          command: |
              curl -fsSL "$GOLANG_DOWNLOAD_URL" -o golang.tar.gz \
                && echo "$GOLANG_DOWNLOAD_SHA256  golang.tar.gz" | sha256sum -c - \
                && sudo tar -C /usr/local -xzf golang.tar.gz \
                && rm golang.tar.gz
              sudo mkdir -p "$GOPATH/src" "$GOPATH/bin" && sudo chmod -R 777 "$GOPATH"
      - run:
          name: tests
          command: |
            export PATH=$GOPATH/bin:/usr/local/go/bin:$PATH
            make build
            make proxy-test &
            make ruby-setup ruby-test
            kill $!

  go-tests:
    docker:
      - image: cimg/go:1.16
      - image: grokzen/redis-cluster:6.0.9
        name: redis-cluster
        environment:
          SENTINEL: 'false'
          STANDALONE: '1'
    environment:
      REDIS_HOST: redis-cluster
    steps:
      - checkout
      - run: make test

  salus:
    machine: true
    steps:
      - checkout
      - run: docker run -t -v $(pwd):/home/repo coinbase/salus

workflows:
  version: 2
  build:
    jobs:
      - go-tests
      - ruby-tests
      - lint
      - salus
