version: '3'

services:
  redis-cluster:
    image: 'grokzen/redis-cluster:6.0.9'
    environment:
      SENTINEL: 'false'
      STANDALONE: '1'
    hostname: server
    ports:
      - '7000-7050:7000-7050'

  go:
    build: ..
    network_mode: host
    image: 652969937640.dkr.ecr.us-east-1.amazonaws.com/containers/golang-1.14:production
    volumes:
      - $PWD:/project
    working_dir: /project
    depends_on:
      - redis-cluster
    environment:
      GONOSUMDB: github.cbhq.net
      GOPROXY: https://gomodules.cbhq.net/

  ruby:
    network_mode: host
    image: 652969937640.dkr.ecr.us-east-1.amazonaws.com/engineering/ruby-2.6-golang-1.13:production
    volumes:
      - $PWD:/project
    working_dir: /project
    depends_on:
      - redis-cluster
    environment:
      GONOSUMDB: github.cbhq.net
      GOPROXY: https://gomodules.cbhq.net/
