version: '3'

services:
  redis-cluster:
    image: 'grokzen/redis-cluster:6.0.9'
    environment:
      SENTINEL: 'false'
      STANDALONE: '1'
    hostname: server
    ports:
      - '7000-7050:7000-7050'

  redisbetween-go:
    build: ..
    network_mode: host
    image: 652969937640.dkr.ecr.us-east-1.amazonaws.com/engineering/golang-1.14:production
    volumes:
      - $PWD:/project
      - /usr/bin/buildkite-agent:/usr/bin/buildkite-agent
    working_dir: /project
    depends_on:
      - redis-cluster
    environment:
      GONOSUMDB: github.cbhq.net
      GOPROXY: https://gomodules.cbhq.net/

  redisbetween-ruby:
    build: ..
    network_mode: host
    image: 652969937640.dkr.ecr.us-east-1.amazonaws.com/engineering/ruby-2.7:production
    volumes:
      - $PWD:/project
      - /usr/bin/buildkite-agent:/usr/bin/buildkite-agent
    working_dir: /project
    depends_on:
      - redis-cluster
