steps:
  - label: lint
    commands:
      - GO111MODULE=on go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.31.0
      - make lint
    env:
      GONOSUMDB: '*'
      GOPROXY: https://gomodules.cbhq.net/
    plugins:
      - file:///buildkite/plugins/docker:
          image: 652969937640.dkr.ecr.us-east-1.amazonaws.com/containers/golang-1.14:production
          propagate-environment: true
    agents:
      queue: docker
  - label: go-tests
    commands:
      - make test
    env:
      GONOSUMDB: github.cbhq.net
      GOPROXY: https://gomodules.cbhq.net/
    plugins:
      - file:///buildkite/plugins/docker-compose:
          run: redisbetween-go
          config: .buildkite/docker-compose.test.yml
          propagate-uid-gid: true
    agents:
      queue: docker
  - label: ruby-tests
    commands:
      - make ruby-test
    plugins:
      - file:///buildkite/plugins/docker-compose:
          run: redisbetween-ruby
          config: .buildkite/docker-compose.test.yml
          propagate-uid-gid: true
    agents:
      queue: docker
